name: Push to DockerHub

on:
  release:
    types:
      - created

jobs:
  push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build -t ${{ secrets.DOCKER_HUB_USERNAME }}/overview-ms:$(echo "${{ github.run_number }}") --push .